shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - jose@4.15.9
  - semver@6.3.1

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
